# User config
author: "liludori"
tagline: "Baby Wishlist"
email: "fulya.aral@gmail.com"
linkedin: "https://www.linkedin.com/in/fulyaagursel"
twitter: "https://twitter.com/liludori"
github: "https://github.com/liludori"

# Site config
baseurl: "/baby-wishlist"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
